"""record what triggered each workflow run

Revision ID: ba6185ebe4e3
Revises: ba6136253bae
Create Date: 2026-08-17 08:07:06.573042

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba6185ebe4e3"
down_revision: str | Sequence[str] | None = "ba6136253bae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_runs", sa.Column("event", sa.String(length=40), nullable=True))
    op.add_column("workflow_runs", sa.Column("actor", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_runs", "actor")
    op.drop_column("workflow_runs", "event")
    # ### end Alembic commands ###
