"""record when each repository was last read from github

Revision ID: 8dfb2cdd72c1
Revises: 2d4aa60648dc
Create Date: 2026-08-17 10:24:12.129589

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dfb2cdd72c1"
down_revision: str | Sequence[str] | None = "2d4aa60648dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repositories", sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "last_synced_at")
    # ### end Alembic commands ###
