"""store pull requests and weekly commit totals

Revision ID: b647dd56d814
Revises: 8dfb2cdd72c1
Create Date: 2026-08-17 10:41:57.842730

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b647dd56d814"
down_revision: str | Sequence[str] | None = "8dfb2cdd72c1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commit_weeks",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("commits", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "week_start", name="uq_commit_weeks_repo_week"),
    )
    op.create_index(
        op.f("ix_commit_weeks_repository_id"), "commit_weeks", ["repository_id"], unique=False
    )
    op.create_table(
        "pull_requests",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("author", sa.String(length=255), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("draft", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("head_branch", sa.String(length=255), nullable=True),
        sa.Column("base_branch", sa.String(length=255), nullable=True),
        sa.Column("html_url", sa.Text(), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("repository_id", "number", name="uq_pull_requests_repo_number"),
    )
    op.create_index(
        "ix_pull_requests_repo_opened",
        "pull_requests",
        ["repository_id", sa.literal_column("opened_at DESC")],
        unique=False,
    )
    op.add_column(
        "repositories", sa.Column("history_synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "history_synced_at")
    op.drop_index("ix_pull_requests_repo_opened", table_name="pull_requests")
    op.drop_table("pull_requests")
    op.drop_index(op.f("ix_commit_weeks_repository_id"), table_name="commit_weeks")
    op.drop_table("commit_weeks")
    # ### end Alembic commands ###
