"""track deployments created by hosting providers

Revision ID: 2d4aa60648dc
Revises: ba6185ebe4e3
Create Date: 2026-08-17 08:29:29.103392

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2d4aa60648dc"
down_revision: str | Sequence[str] | None = "ba6185ebe4e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deployments", sa.Column("github_deployment_id", sa.BigInteger(), nullable=True))
    op.create_unique_constraint(
        "uq_deployments_repo_github_id", "deployments", ["repository_id", "github_deployment_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_deployments_repo_github_id", "deployments", type_="unique")
    op.drop_column("deployments", "github_deployment_id")
    # ### end Alembic commands ###
