"""track commit stat collection apart from pull requests

Revision ID: 4e0000c21f6d
Revises: b647dd56d814
Create Date: 2026-08-17 11:08:05.070804

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e0000c21f6d"
down_revision: str | Sequence[str] | None = "b647dd56d814"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "repositories", sa.Column("commits_synced_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("repositories", "commits_synced_at")
    # ### end Alembic commands ###
