"""keep the github refresh token so access renews itself

Revision ID: e0e10f5795d3
Revises: 4e0000c21f6d
Create Date: 2026-08-17 23:08:49.325408

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0e10f5795d3"
down_revision: str | Sequence[str] | None = "4e0000c21f6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("refresh_token_encrypted", sa.Text(), nullable=True))
    op.add_column(
        "users", sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "access_token_expires_at")
    op.drop_column("users", "refresh_token_encrypted")
    # ### end Alembic commands ###
