"""raise an alert when a pipeline breaks

Revision ID: 664a820e542e
Revises: e0e10f5795d3
Create Date: 2026-08-18 09:40:56.733427

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "664a820e542e"
down_revision: str | Sequence[str] | None = "e0e10f5795d3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("repository_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("issue_number", sa.Integer(), nullable=True),
        sa.Column("issue_url", sa.Text(), nullable=True),
        sa.Column("raised_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["repository_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_repository_id"), "alerts", ["repository_id"], unique=False)
    op.create_index(
        "uq_alert_open",
        "alerts",
        ["repository_id", "subject"],
        unique=True,
        postgresql_where=sa.text("resolved_at IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_alert_open", table_name="alerts", postgresql_where=sa.text("resolved_at IS NULL")
    )
    op.drop_index(op.f("ix_alerts_repository_id"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
